spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jogobixoapi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306
    schemas: jogobixoapi
    user: root
    password: root
